os: osx
osx_image: xcode8.3
language: objective-c

notifications:
  email: false

cache: 
  - bundler

install:
  - gem install bundler
  - gem install nokogiri -- --use-system-libraries
  - bundle install

script: 
  - bundle exec fastlane coverage ci:true
